### ISSUE TITLE
magit: keybindings don't match with help

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#102]
Hey,

very cool .emacs.d organization. I'm pretty sure I will be migrating some of my stuff over. So thanks for this!

I've noticed that L is shown twice, stashing is upper case z but regular z is displayed.

Essentials commands:
g for reset is gr
C-h m show all key bindings are f1 m, as SPC is used to select a commit

best regards,
benny

**Comment by hlissner** [comment]
I've decided to simplify things a little with magit. I've tried too hard to "evil-ify" magit; it's too much effort for too little reward. So I've removed `evil-magit` and left magit to run in Emacs mode with its default bindings. It's easy enough to toggle evil with `C-z` if needed.

This should fix both issues, but it also means that `SPC` and `SPC m` are inaccessible from emacs mode in magit. Not sure how disruptive that could be. I'll think about it.

**Comment by bandresen** [comment]
That's very confusing.

In my current config I also use evil-magit and I don't have wrong keybindings. I will have to investigate why this is the case as I didn't have that many problems with evil-magit so far.

**Comment by hlissner** [comment]
Sorry about that. I'm not familiar enough with magit at this stage to make an educated judgement on the matter, but it has become routine to encounter a new magit function, then discover that its keybinding is shadowed; usually by my own bindings. Followed by a rebinding dance, rinse and repeat.

So that got me thinking if `evil-magit` even belonged in `feature/version-control` in the first place. Perhaps a private module would be a better fit, rather than force evil-magit on evil users.

That's my reasoning anyway. I may restore it in the future, but for now I leave it to users to put in their private modules.

**Comment by bandresen** [comment]
Found the culprit for some of my confusion. My own emacs.d had a evil-magit from June 2016 and they had an update in November that changed a bit.

Also doom defaults to horizontal movement enabled, which means l turns to L but L is already within in evil-magit Changelog, which is just a bug in evil-magit.

The only real incompatibility for now is evil-vimish-fold-mode on z which is shadowing stash. I'll keep using evil-magit while disabling vimish in magit buffers. Thanks!

**Comment by hlissner** [comment]
Nice work, and that's good to know! I'll consider this resolved then.
