### ISSUE TITLE
emacsclient $FILE shows dashboard instead of $FILE

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#119]
Latest HEAD

Start up emacs regularly.
emacsclient -c /tmp/testfile

A new emacs frame is launched, the file is opened in that frame and then the dashboard is shown.
C-x b RET and the file is shown.

**Comment by hlissner** [comment]
I'm aware of the problem and know how to fix it. I'll take a look at it tonight.

**Comment by hlissner** [comment]
I've pushed a fix for this that I'm not entirely happy with. It's a hack.

So far I've found no reliable way to detect that specific scenario where 1) `server-start` is called from an interactive session of Emacs, and 2) `emacsclient` creates a new frame, 3) but _without_ file arguments.

I can't check "the current buffer" from `after-make-frame-functions` because its run before the frame's buffer list has been initialized. So instead, I wait 0.1 seconds and _then_ check what the situation is (is a file loaded? Yes? Then forget the dashboard. No? Then open it). So it's a hack. On a sufficiently slow computer, I'm unsure if this will break.

There's `server-visit-hook`, but annoyingly enough it is only called when file arguments are present. I'll dig through server.el for alternatives, but for now I'll consider this resolved. Feel free to reopen if you still have problems.

**Comment by deybhayden** [comment]
Is this a thing that possibly crept back into `develop`? I'm running into it right now.

**Comment by hlissner** [comment]
@deybhayden Yes it did; I just fixed it. Let me know if it hasn't resolved your issue.
