### ISSUE TITLE
Any advice/suggestions on emacs config development workflow?

### ISSUE THREAD

**Issue by orther** [hlissner/.emacs.d#124]
## Why I'm asking
I'm fairly new to writing elisp and customizing emacs. Only since moving from Spacemacs to Doom a few months ago have I started to heavily customize my emacs configuration. My current process feels far from ideal and inefficient.

### My current workflow looks like:
1.  Make some change(s) to my private module and/or `~/.emacs.d/init.el`
1. `M-x doom/recompile` and/or `M-x doom/reload` 
1. If things aren't working how I expect I will often close Emacs, run `make`, and start it with `emacs --init-debug`
1. If the cause of the problem isn't obvious from the shown error message on Emacs start I don't really know where to go besides general development debugging techniques like commenting out lines until it works 😄 

(NOTE: I do run `make doctor` but it always says "Everything seems fine")

## What I'm looking for
Any advice to help better my emacs config development workflow. More specifically: 
 - What steps do more experienced emacs users take when making changes to their emacs config?
   - Anything specific to Doom?
   - Anything specific to working on a Doom private module?
 - Can I do anything to help track down bugs?
   - _For example I thought changes to my private module caused the (recently fixed upstream) undo corruption bug. Is there anything I could do to track the cause down besides general development techniques like `git bisect`?_

**Comment by hlissner** [comment]
My apologies for a late reply. It's a difficult question, but here's what jumps out at me:

+ Not sure if it was a typo, but it's `emacs --debug-init`, not `emacs --init-debug`.
+ The equivalent of `--debug-init` is `M-x toggle-debug-on-error`.
+ Don't debug byte-compiled code. It will interfere. Clean up byte compiled code with `make clean` and restart Emacs.
+ You could save yourself time by knowing when `doom/reload`, `make doctor` and `make` are appropriate to call.
  + `doom/reload` resets the `load-path`. You rarely, if ever, need to use it, unless you're messing around with packages by hand, outside of Emacs. All package management commands that might cause an out-of-sync load-path call `doom/reload` remotely (even from make commands). Restarting Emacs is equivalent to calling `doom/reload`.
  + `make doctor` clumsily diagnoses issues with your OS/environment that could interfere with Emacs (e.g. an older version of emacs in your PATH, your system is misconfigured for verifying TLS certificates, git isn't installed, etc). If it produces no issues once, it's unlikely to next time (unless you update your OS, Emacs or similar).
  + `make` is the equivalent of `make autoloads autoremove install`, as in: it regenerates the autoloads file, autoremoves unused packages and installs missing packages. It's harmless to over use, but you are unlikely to need all three. This umbrella task's primary use-case is after updating Doom from upstream, when you can't be certain of what has changed.
    + If you're getting missing-package errors, `make install` might help.
    + Getting missing function/variable errors? `make autoloads` might help.
    + `make autoremove` would only help if an unneeded, installed package was overshadowing another, somehow. That is to say, it is unlikely to help you when debugging.

> What steps do more experienced emacs users take when making changes to their emacs config? 

There isn't anything particular about the workflow of an experienced Emacs user. It simply has fewer diagnostic steps when something goes wrong, guided by an intuition they've collected throughout the process of writing their configs from scratch and vetting every plugin they've incorporated into them. I'm afraid there's no substitute for that.

But with Doom in particular, perhaps these can help:

+ If you modify any module's autoload functions, run `make autoloads`
+ If you remove `package!` forms from any module's `packages.el` file, run `make autoremove`
+ If you add `package!` forms to any module's `packages.el` file, run `make install`
+ If you modify `init.el` or update Doom from upstream, run `make` (equivalent to `make autoloads autoremove install`)
+ If you suspect Doom core is causing a problem, run the unit tests with `make test`.
+ I iterate on my config so often that I don't byte-compile all of it. I only byte-compile Doom core (with `make compile:core`). Unless the error is _in_ Doom core, this removes the need to run `doom/recompile` after every change.
+ Do you know about `describe-function`, `describe-variable` and `describe-key`? Use them frequently. Investigate every variable before you change them and every function before you call them. If an error happens as a result of you invoking a command bound to some key, you can find out what command is bound to a key with `describe-key`.
+ Are you familiar with the Emacs debugger? You can set `debug-on-error` to `t` with `M-x toggle-debug-on-error` or `emacs --debug-init`, but there's also `debug-on-signal`, `debug-on-message`, `debug-on-quit` and `debug-on-event`.
+ Doom has two custom help commands: `doom/describe-setting` and `doom/describe-module`.
+ Doom has unit tests, but their coverage (at the time of writing) is abysmal. It's a WIP. It may help to write your own for your own private modules, and you can run these tests with `make test`, or a specific module's tests with--for example--`make test:feature/evil`, or all the unit tests in a group with `make test:feature`.

> Can I do anything to help track down bugs? 

Unfortunately, there is no silver bullet. Even if I could guarantee Doom's stability, it still relies on 250+ 3rd party plugins. That's a lot of surface area it can't reasonably cover. If you can't get the debugger to produce a backtrace, then git and comment bisection are your best bet (Doom's `init.el` should make that easier). Finding the source is half the battle. 

And of course, don't hesitate to post your issue here.

---

I hope some of that has helped you. I make no assumptions about your background, so I apologize if none of it is new to you.

**Comment by orther** [comment]
When I opened this issue I considered it possibly too general to make sense as an issue in this repo but figured you could close it if you agreed. What you provided is exactly the information I was hoping for. I really appreciate the thorough response. Thanks!

---

(NOTE: I'm closing this since I am satisfied and don't see any reason to keep it open.)
