### ISSUE TITLE
Generalize online search functionality

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#140]
I recently made a few updates to your built in online searching functionality that I thought you might find interesting. Currently there exists a single function ```+jump/online``` which essentially allows you to lookup the thing under point using an online search provider you select. It will cache your selected provider and will use that same provider going forward.

I've basically made this functionality more generic and have exposed it via four separate functions:

1) ```(defun +search/online (&optional where search) ...)``` - This function is the main driver that performs an online search. If ```where``` is missing, it will prompt the user to select a search provider. If the ```search``` argument is missing, then it will first check if there is an active selection to use, otherwise if there is no active selection, it will prompt the user for a search query. It also updates the variable ```+search--online-last``` with the chosen search provider.

2) ```(defun +search/online-use-last (&optional search) ...)``` - This function basically invokes ```+search/online``` using the previous search provider if it exists.

3) ```(defun +jump/online (&optional where) ...)``` - This function delegates to ```+search/online``` using the thing under point as the search query.

4) ```(defun +jump/online-use-last () ...)``` - This function invokes ```+jump/online``` using the previous search provider as an argument if it exists. This is essentially what ```jump/online``` does now.

You can find these functions implemented in this commit:

https://github.com/gilbertw1/bmacs/commit/6401c79b6721964973c3e75d512e9422f686e7b8

Using ```+search/online-use-last``` plus an active selection, is very useful for googling error messages in a single step.

Just thought I'd point this out in case you're interested. If you would like this functionality merged in feel free to pull the functions over (and probably improve them), or if you'd like me to create a pull request, I could do that as well.

Thanks!

**Comment by hlissner** [comment]
That looks great! I was planning to do this myself. I'll have a closer look at it over the weekend and decide how to go about bringing it over to Doom.

**Comment by hlissner** [comment]
I ended up generalizing `+jump/online` so that it does the equivalent of your `+search/online`.

+ Uses the selection if region is active.
+ If region isn't active, it prompts for the search query, with thing-at-point as the initial input.
+ On first use, it prompts for a provider. On consecutive uses it reuses the last provider.
+ If the universal argument is supplied, e.g. `C-u M-x +jump/online`, the prompt is forced to appear.

For posterity, the universal argument is bound to `SPC u` in my private Doom bindings. If you aren't an evil user, it is bound to `C-u` by default. A hacky alternative is to use evil's digit prefixes. e.g. `1 M-x +jump/online` is the equivalent of `SPC u M-x +jump/online`. What number you use doesn't matter, it counts as a present universal argument.

In any case, I'll consider this resolved. Thank you for sharing; it is a great help!

**Comment by gilbertw1** [comment]
Awesome! 👍 

Also, I was curious if you had seen this: https://github.com/nilcons/emacs-use-package-fast

Looks like a pretty neat hack, but I don't quite understand the package logic well enough yet to determine if this would help speed up the Doom load time or not.

**Comment by hlissner** [comment]
Interesting find, I hadn't seen it, but you'll be happy to know that Doom already employs the optimizations he uses. I forgo package.el's native initialization for my own in [doom-initialize](https://github.com/hlissner/.emacs.d/blob/master/core/core-packages.el#L136), which is [evaluated at compile time](https://github.com/hlissner/.emacs.d/blob/master/core/core.el#L178). On top of that, I [defer garbage collection](https://github.com/hlissner/.emacs.d/blob/master/core/core.el#L157) until as late as possible (on `emacs-startup-hook` instead of `after-init-hook`, because it happens later).

Good stuff!

**Comment by gilbertw1** [comment]
Hah, that's awesome! I'm not surprised though, your doing god's work here :)
