### ISSUE TITLE
Buffer list order

### ISSUE THREAD

**Issue by aminb** [hlissner/.emacs.d#144]
I'd like to have my list of buffers in the switcher be sorted the usual way, according the time of last use, and also have the most recently used buffer (aside from the current one) be on the top of the list and focused so I can just press enter and switch to it.

I tried tweaking `ivy-sort-functions-alist` but I couldn't get what I wanted. Am I looking at the wrong place?

**Comment by hlissner** [comment]
Yes, because `+ivy/switch-buffer` doesn't let ivy handle sorting at all.

In either case, this is a bug. I want buffer listings to be ordered by recency, so:

Quick question: are you using `:feature workspaces` (and persp-mode)? If you are, then the buffer list is retrieved from `+workspace-buffer-list`, which in turn relies on `persp-mode`'s buffer list, which isn't sorted by recency.

If that's the case, try adding this code:

```emacs-lisp
(defun my-workspace-buffer-list (&optional persp)
  (unless persp
    (setq persp (get-current-persp)))
  (if (eq persp t)
      (cl-remove-if #'persp--buffer-in-persps (buffer-list))
    (when (stringp persp)
      (setq persp (+workspace-get persp t)))
    (cl-loop for buf in (buffer-list)
             if (persp-contain-buffer-p buf persp)
             collect buf)))
(advice-add #'+workspace-buffer-list :override #'my-workspace-buffer-list)
```

And tell me if it fixes your issue. If it does, I will replace `+workspace-buffer-list` with this function.

**Comment by aminb** [comment]
Ah I see, that makes sense.

> Quick question: are you using :feature workspaces (and persp-mode)? 

Yup, I am! Your snippet sorts them by recency, but I still have one small gripe with it: the current buffer sits on the top, whereas ideally the current buffer should be the second on the list and the first item on the list should be the second most recently used buffer (i.e. the most recently used one, aside from the current buffer). This way I'd be able to switch back and forth between the two most recent buffers by doing <kbd>C-x</kbd><kbd>b</kbd><kbd>return</kbd> (or <kbd>SPC</kbd><kbd><</kbd><kbd>return</kbd> with your keybindings).

**Comment by hlissner** [comment]
Ah, I had intended for the current buffer to be omitted entirely from the buffer list (which should accomplish what you wanted). I've pushed both fixes to `develop`. It'll make its way into master within the next day or two.

**Comment by aminb** [comment]
Great, that works; thanks!
