### ISSUE TITLE
Icons broken by default, 'make doctor' not helpful

### ISSUE THREAD

**Issue by int-index** [hlissner/.emacs.d#167]
When I open the editor, it displays incorrect unicode symbols:

![image](https://user-images.githubusercontent.com/4061728/28989953-8acbe6c0-7981-11e7-9cf3-37a383b8c52a.png)

Then, if I enable `unicode` in `init.el`, the entire Emacs window is just blank, white.

![image](https://user-images.githubusercontent.com/4061728/28989997-e3f8f77e-7981-11e7-8d7b-1fbfbb25bf20.png)

it loads 100% CPU, and after about a minute displays the default screen, with unicode symbols being still broken:

![image](https://user-images.githubusercontent.com/4061728/28990024-226c3ee4-7982-11e7-8599-cfb3b77a81ff.png)

Finally, when I try to run `make doctor`, I receive the following errors:

```
.emacs.d(master)*$ DEBUG=1 make doctor
DOOM Doctor
Running Emacs v26.0.50, commit 5fe3cfbc75ba25f8c25f2633d21f2c7f29281a1e

Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY
  LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD
uname -a:
  Linux forlorn-ruins 4.10.0-30-generic #34~16.04.1-Ubuntu SMP Wed Aug 2
  02:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Attempt to load DOOM: success! Loaded v2.0.4
Revision 5fe3cfbc75ba25f8c25f2633d21f2c7f29281a1e

----

Verified elpa.gnu.org
Verified melpa.org
peculiar error
Makefile:75: recipe for target 'doctor' failed
make: *** [doctor] Error 255
```

**Comment by int-index** [comment]
The icons can be fixed with `M-x all-the-icons-install-fonts`, perhaps add it to the README? The `doctor` command still fails.

**Comment by hlissner** [comment]
You're right. I'm in the process of rewriting my readme (and adding more documentation in general). This will be mentioned in the new quick start section.

In the meantime, I've added font detection to the doctor. It will complain if all-the-icons fonts are missing (and tell you to run `M-x all-the-icons-install-fonts` if you don't).

On another note: the `ui/unicode` module is unrelated to icon fonts. It's more for non-English speaking users who need better language support, but I realize that isn't obvious. I'll work on that!

I'll keep this issue open until the new readme + documentation comes up.

**Comment by amoriello** [comment]
Following up on this:

@hlissner: please don't make all-the-icons mandatory in make install. It will break terminal users (especially remote ssh users). Have you considered using  this? https://github.com/sebastiencs/icons-in-terminal. It would be great to have either all-the-icons or icons-in-terminal support based on UI mode or not.

BTW, I know this config is not so much about terminal users, but it's mostly working fine, and I love it. Please, don't break it ❤️

**Comment by hlissner** [comment]
@amoriello Not to worry, I have no intention of making it mandatory. I'm very tempted to switch to icons-in-terminal, not for terminal support specifically, but because its API is simpler. Sadly, it is low priority and is non-trivial, so it'll get a tentative "whenever I get around to it".

---

In any case, I've included this problem in the [FAQ](https://github.com/hlissner/.emacs.d/wiki/FAQ) under [troubleshooting](https://github.com/hlissner/.emacs.d/wiki/FAQ#troubleshooting), and talk about it in the ["Post-installation tips" section of the new installation guide](https://github.com/hlissner/.emacs.d/wiki/Getting-Started#post-installation-tips), including a link to the wiki in [project readme](https://github.com/hlissner/.emacs.d/tree/develop#quick-start) (albeit on the `develop` branch, for now).

It's still a WIP, but I'll consider this resolved.
