### ISSUE TITLE
v2 - feature deps

### ISSUE THREAD

**Issue by yintothayang** [hlissner/.emacs.d#38]
Messing around with your new v2, love v1.  I'm not an `evil` person, so I removed the `evil` feature from init.el. 

This breaks the conf, as other `features` take dependencies on this `feature`.  This doesn't feel right, as it should probably go into `core` if other things take dependency on it. 

I know you're in the middle of a re-write, so I was just curious if you planned on doing this, or had any advice to a non-evil user. 

thanks!

**Comment by hlissner** [comment]
i've tried to ensure that there are no _hard_ dependencies between modules, evil included, _however_ there is one in my private module [where I bind to the evil-window-map keymap](https://github.com/hlissner/.emacs.d/blob/v2/modules/private/hlissner/%2Bbindings.el#L233); this causes an error if evil isn't enabled/loaded (the keymap isn't defined). This was an oversight, so I'll fix it soon.

Otherwise I know of no other. Delete that `(:map evil-window-map ...)` block and Emacs should run fine without evil. Are there other issues you've encountered?

There _are_ `(after! evil ...)` and `(when (featurep! :feature evil) ...)` blocks here and there, some of whom can be safely removed, but they're very few, unintrusive and won't hinder performance. 

The real problem is my private module (`modules/private/hlissner`), which is _heavily_ evil oriented. I'd suggest:

1. Copy `modules/private/hlissner` to, say, `modules/private/yintohayang` and then:
2. Replace `:private hlissner` with `:private yintohayang` in init.el.
3. In `modules/private/yintohayang`, delete +commands.el; these are filled with evil-ex commands -- unnecessary without evil.
4. You'll want to rewrite +bindings.el; my bindings were designed from the perspective of an evil user, and I'm not sure how useful that is to you. Sorry to say I have little insight into the workflow of a vanilla Emacs user, so I can't advise on keybindings, but maybe you can find some inspiration from my +bindings.el.

  At least, you'll want to delete any `map!` bindings that bind to an evil state (they started with :i :n :v :o :r and/or :e -- or some combination of those). Those are ignored by `map!` if evil isn't loaded anyway, so they're safe to remove (or keep).

5. Modify `modules/private/yintohayang/config.el`. Remove the `(load! +commands)` call and the `(after! evil ...)` block, along with the `+my!repeat-with-spc` macro. None of that applies to you.

After all that, you should be good to go. I hope that helped!

**Comment by yintothayang** [comment]
👍  thanks
