### ISSUE TITLE
Want any of these as pull requests?

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#51]
Hey, I've been having a great time building on your config and making it my own. I've made a good number of changes (many extracted from Spacemacs), and I was wondering if you'd like me to create pull requests for any of the following:

* Evil MC - I liked evil multiedit, but it's nice being able to arbitrarily place cursors. I saw your note about evil-mc not working, but I was able to integrate it just fine
* Neotree - Automatically hide tree on enter file
* Neotree - better evil keybindings (h - up tree/collapse, j - down, k - up, l - enter file / expand dir)
* Gist.el - create gists from region or buffer
* Large File - Prompt to open large file (size threshold configurable) in read-only fundamental mode for massive perf improvement
* restclient mode - Super awesome amazing tool for creating rest requests
* better interactive copy / rename / delete (current and other) file functions
* winum mode - quick select window by number
* auto indent on paste
* jump most recent buffer

I figured I'd just create an issue and see if you were interested in any of these changes before I started creating pull requests. I'll submit bug PR's right away, but I realize many of these are more personal preference. Thanks again for this ... your configs and themes are killer

**Comment by hlissner** [comment]
That's a fantastic list, thank you for the offer! I'd appreciate a PR for:

+ `evil-mc`: I tried evil-mc a _long_ time ago, so I wouldn't be surprised if it'd work now, and I look forward to finally having a proper multiple-cursor implementation in Emacs!
+ `Large File`
+ `Neotree - better evil keybindings`

A few fyi's about other items on your list:

+ winum-mode: I have something similar in place already (avy) via `M-x ace-window` (bound to `C-w C-w` by in my bindings).
+ restclient-mode: I already have this in `modules/lang/rest`; a fantastic tool! I use it in combination with org-babel to test (and annotate) REST requests and test APIs.
+ auto indent on paste: I was tempted, but decided against it because not all major modes have good [enough] indentation functions (like yaml-mode, or python-mode/sh-mode in some cases) for me to trust to automation.

    Also: In case you didn't know, I have a [+evil/reselect-paste](https://github.com/hlissner/.emacs.d/blob/master/modules/feature/evil/autoload/evil.el#L22) command bound to `gp` that makes it much easier to reindent pasted blocks manually (e.g. `pgp=`).
+ gist.el: I intend to add [webpaste.el](https://github.com/etu/webpaste.el) to my config soon, which provides access to several pastebin services, including gists. I'll write ex commands for it too.

Anyhow, thank you for the kind words and good work!

**Comment by gilbertw1** [comment]
Cool, I'll create those pull requests soon!

I totally missed the fact that you had restclient in already in the config. I tried to pull over all the things I wanted to keep piecemeal, but I'm still finding new (and awesome) things as I continue to mine through the config. Also, I think I'll actually be removing winum-mode, ace-window is actually a much better solution. Thanks for pointing that out.

It's been fun learning elisp as I go along, I think my favorite find so far is ```advice-add```, I fully expect to do both great and terrible things with this in the future.
