### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by shanbhardwaj** [hlissner/.emacs.d#66]
I'm using 
GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)

After cloning the repo and running make install I get the following, including with the DEBUG=1 flag.
```

Symbol's function definition is void: set-charset-priority
make: *** [autoloads] Error 255
```

**Comment by hlissner** [comment]
Where did you download emacs from? Through homebrew (if so, what options did you use)? From emacsformacosx.com? Perhaps elsewhere?

I ask because `set-charset-priority` is a built-in C function, so that means a module wasn't compiled when your emacs was built. If you downloaded a pre-made binary from a site like emacsformacosx.com, it means they didn't compile it with this module's support.

It's an easy fix, but I need to ask a favor: could you open Emacs with a blank config (`emacs -Q`) and run: `M-x describe-function` and then look for the following functions:

+ prefer-coding-system
+ set-terminal-coding-system
+ set-keyboard-coding-system
+ set-selection-coding-system

I need to know which of these exist for you.

**Comment by hlissner** [comment]
Actually, nevermind. The four of those are defined in mule.el, which should be included with Emacs. I'll push a fix for this soon.

**Comment by hlissner** [comment]
That should do it. Feel free to reopen this if it persists.
